apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 2000Gi