apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      namespace: jellyfin
    spec:
      runtimeClassName: nvidia
      containers:
      - image: nyanmisaka/jellyfin:240401-amd64
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
          - containerPort: 8096
            name: jellyfin
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
          - mountPath: /config
            name: jellyfin
            subPath: docker/jellyfin
          - mountPath: /data
            name: jellyfin
            subPath: Media/Movies
        resources:
          limits:
            nvidia.com/gpu: 1 
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
      restartPolicy: Always
      volumes:
        - name: jellyfin
          persistentVolumeClaim:
            claimName: jellyfin-pvc
