apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
      namespace: homelab
    spec:
      containers:
      - image: deluan/navidrome:0.52.5
        imagePullPolicy: IfNotPresent
        name: navidrome
        ports:
        - containerPort: 4533
          name: navidrome
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
        - mountPath: /config
          name: media
          subPath: docker/navidrome
        - mountPath: /music
          name: media
          subPath: Media/Music
        - name: navidrome-secret
          mountPath: "/etc/secret"
          readOnly: true
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: ND_DEFAULTLANGUAGE
          value: zh-Hans
        - name: ND_ENABLEGRAVATAR
          value: 'true'
        - name: ND_MUSICFOLDER
          value: /music
        - name: ND_DATAFOLDER
          value: /config
        - name: ND_LASTFM_ENABLED
          value: 'true'
        - name: ND_LASTFM_APIKEY
          valueFrom:
            secretKeyRef:
              name: navidrome-secret
              key: ND_LASTFM_APIKEY
        - name: ND_LASTFM_SECRET
          valueFrom:
            secretKeyRef:
              name: navidrome-secret
              key: ND_LASTFM_SECRET
        - name: ND_SPOTIFY_ID
          valueFrom:
            secretKeyRef:
              name: navidrome-secret
              key: ND_SPOTIFY_ID
        - name: ND_SPOTIFY_SECRET
          valueFrom:
            secretKeyRef:
              name: navidrome-secret
              key: ND_SPOTIFY_SECRET
        - name: ND_LASTFM_LANGUAGE
          value: zh
        - name: ND_LOGLEVEL
          value: info
      restartPolicy: Always
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: navidrome-secret
          secret:
            secretName: navidrome-secret