apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
  namespace: homelab
spec:
  ports:
  - name: http
    port: 4533
    protocol: TCP
    targetPort: 4533
  selector:
    app: navidrome
  type: ClusterIP
